#!/usr/bin/env bash
# script that prints a phrase 10 times and inserts a special message on the 9th iteration

i=1 

while [ $i -le 10 ]  
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done

