#!/usr/bin/env bash

# Script to print numbers from 1 to 10 
# Using a while loop

i=1

# Loop while i is less than or equal to 10
while [ $i -le 10 ]  
do

  # Check if i is 4
  if [ $i -eq 4 ]    
  then
    echo "bad luck"
  
  # Check if i is 8  
  elif [ $i -eq 8 ]
  then
    echo "good luck"

  # For all other i  
  else
    echo "Best School"
  fi

  # Increment i by 1
  ((i++))   
done

