#!/usr/bin/env bash

# This script displays numbers from 1 to 20
# It prints special messages on numbers 4, 9, and 17

i=1

while [ "$i" -le 20 ]  
do
  echo "$i"

  # Check if i is 4, 9, or 17 and print special message
  case $i in 
    4)
      echo "bad luck from China"
      ;;
    9)  
      echo "bad luck from Japan" 
     ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac

  # Increment i by 1
  i=$((i + 1))
done

# i will end up with a value of 21 after the loop finishes

